version: "3.7"
services:
  php:
    build: '.docker/php/'
    networks:
      - backend
    volumes:
      - ./public/:/var/www/html/
  apache:
    build: '.docker/apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
networks:
  frontend:
  backend: